# Generated by Django 3.0 on 2020-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
